name: ci-1-private-docker-action

run-name: call private docker action directly 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: joshjohanning-org/simple-docker-action/private@main
