name: ci-3-local-composite-action-calls-private-docker-action

run-name: call composite action that contains private docker action 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: auth to acr
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login --username test123j --password-stdin test123j.azurecr.io
      - uses: ./composite-action-private-registry-docker-actions
