name: ci-6-nest-composite-action-in-remote-composite-action

run-name: nest composite action in remote composite action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joshjohanning-org/composite-action-private-registry-docker-actions/nested-composite-action@main
        with:
          acr-secret:  ${{ secrets.ACR_PASSWORD }}
        continue-on-error: true
