name: ci-7-nest-composite-action-in-remote-composite-action-better

run-name: nest composite action in remote composite action better

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: simple-docker-action
        uses: joshjohanning-org/composite-action-private-registry-docker-actions/nested-composite-action-better/1-action@main
        with:
          password:  ${{ secrets.ACR_PASSWORD }}
